# Generated by Django 5.2.10 on 2026-01-09 00:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reminder_type",
                    models.CharField(default="medication", max_length=20),
                ),
                ("scheduled_time", models.TimeField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reminders",
                "ordering": ["scheduled_time"],
            },
        ),
    ]
